#!/bin/sh

cd "$1"

PATCH_GO_VERSION=$(egrep '^go ' go.mod | awk '{print $2}' | sed -e 's+^\([0-9]*\.[0-9]*\)[^0-9]*.*$+\1+')
PATCH_GO_PATH="$(ls -d ${RUNNER_TOOL_CACHE}/go/${PATCH_GO_VERSION}.*/*/bin)"
export PATH="${PATH}:${PATCH_GO_PATH}"

echo "Patching go dependencies to address vulnerabilities"

echo "Bumping azure-sdk-for-go/sdk/azidentity dependency version to v1.6.0"
go get github.com/Azure/azure-sdk-for-go/sdk/azidentity@v1.6.0

echo "Patching go.mod to use the patched trivy-kubernetes library"
cat - >> go.mod << EOF

replace (
       github.com/aquasecurity/trivy-checks => github.com/aquasecurity/trivy-checks v0.0.0-20240430045208-6cc735de6b9e
       github.com/aquasecurity/trivy-kubernetes => github.com/aquasecurity/trivy-kubernetes v0.0.0-20240626072334-56e5b9a42649
)
EOF

echo "Bumping go-getter dependency version to v1.7.5"
go get github.com/hashicorp/go-getter@v1.7.5

echo "Running go mod tidy"
go mod tidy

echo "Running clean of the modcache"
go clean -modcache
